all:
	go run hw2_1.go data.go message.go mode.go node.go

b: 
	go run hw2_1.go data.go message.go mode.go node.go -b
w: 
	go run hw2_1.go data.go message.go mode.go node.go -w
f: 
	go run hw2_1.go data.go message.go mode.go node.go -f
ff: 
	go run hw2_1.go data.go message.go mode.go node.go -ff
m: 
	go run hw2_1.go data.go message.go mode.go node.go -m
d: 
	go run hw2_1.go data.go message.go mode.go node.go -d
runb:
	./hw1_3
build:
	go build hw2_1.go data.go message.go mode.go node.go
clean:
	go clean